# Generated by Django 5.0.6 on 2024-06-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderator', '0002_rename_titel_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moderator.song')),
            ],
        ),
    ]
