# Generated by Django 5.0.6 on 2024-06-22 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0005_remove_gameday_attributes'),
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='song',
        ),
        migrations.AddField(
            model_name='singer',
            name='gameday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moderator.gameday'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SingerSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('planned_order', models.IntegerField()),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.singer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.song')),
            ],
        ),
    ]
