# Generated by Django 5.0.6 on 2024-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_rename_titel_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField(null=True)),
                ('attributes', models.ManyToManyField(to='moderator.attribute')),
                ('genre', models.ManyToManyField(to='moderator.genre')),
            ],
        ),
    ]
