# Generated by Django 5.0.6 on 2024-06-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_remove_gameday_genre_gameday_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameday',
            name='attributes',
        ),
    ]
